// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB06hBsE644dYze3ARNUaP97AcBpULyKfg',
    appId: '1:726316209501:web:6eeee77e4afa7711e084b4',
    messagingSenderId: '726316209501',
    projectId: 'mmctest-18030',
    authDomain: 'mmctest-18030.firebaseapp.com',
    storageBucket: 'mmctest-18030.appspot.com',
    measurementId: 'G-LT36CVD3P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-7nr_2dHsjfkSGC10npEs2L7rufs2Twc',
    appId: '1:726316209501:android:410a50a458b400b1e084b4',
    messagingSenderId: '726316209501',
    projectId: 'mmctest-18030',
    storageBucket: 'mmctest-18030.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvQHhaEvYmZI4hZU373aBObtri8Dc59V0',
    appId: '1:726316209501:ios:aff0106b0a746df0e084b4',
    messagingSenderId: '726316209501',
    projectId: 'mmctest-18030',
    storageBucket: 'mmctest-18030.appspot.com',
    iosBundleId: 'com.group.MCC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvQHhaEvYmZI4hZU373aBObtri8Dc59V0',
    appId: '1:726316209501:ios:608c869f962289d2e084b4',
    messagingSenderId: '726316209501',
    projectId: 'mmctest-18030',
    storageBucket: 'mmctest-18030.appspot.com',
    iosBundleId: 'com.group.MCC.RunnerTests',
  );
}
